### ISSUE TITLE
Meta 4: Gerenciar de forma prática os status dos alunos graduandos.

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#130]
- [ ] US1: Consultar lista de alunos graduandos não aptos. **Complexidade**: baixa. 🏭
- [ ] US2: Verificar os requisitos: Ata, Lauda e CD. **Complexidade**: baixa. 🏭
- [ ] US3: O aluno é removido da lista de alunos graduandos não aptos. **Complexidade**: baixa. 🏭
- [ ] US4: O aluno é adicionado à lista de alunos graduandos aptos. **Complexidade**: média. 🏭

**Comment by daniel-santana** [comment]
Uma pessoa do Front End vai ter que verificar caso tenha mudado.

**Comment by lubien** [comment]
@daniel-santana você esqueceu de marcar tudo
