### ISSUE TITLE
Meta 10: Gerar lista de alunos presentes na lista de prescrição

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#132]
- [x] US1: Selecionar o curso. **Complexidade**: baixa. 🖼️
- [x] US2: Selecionar grupo de formandos. **Complexidade**: baixa. 🖼️
- [x] US3: Selecionar botão para gerar alunos na lista de prescrição. **Complexidade**: baixa. 🖼️ (Implementado em #141)
- [x] US4: Consultar alunos presentes na lista de graduandos aptos, graduandos não aptos e formandos. **Complexidade**: baixa. 🖼️🏭(Back-end Implementada em #141)
- - [x]  A consulta deve ser realizada no campo referente ao atributo lista de prescrição. 
- [x] US5: Selecionar alunos com atributo "lista de prescrição" selecionado. **Complexidade**: baixa. 🏭 (Implementado em #141)
- [x] US6: Gerar lista de alunos presentes na lista de prescrição. **Complexidade**: baixa. 🖼️🏭(Back-end Inplementada em #141)
- - [x] Na lista gerada deve aparecer o nome do aluno e a respectiva lista a que ele pertence(graduando-apto, graduando-não-apto e formando).

**Comment by lubien** [comment]
Há a possibilidade de que a flag `prescribed` seja desnecessária. Se sim, avisar o @Jamadhar .

**Comment by lubien** [comment]
Recomendação: GET `/api/students/?prescribed=1`.

Filtraria: `students` (graduandos e formandos) que tem um `documents` que seja do `type` `3` (lista de prescrição)
