### ISSUE TITLE
Meta 11: Gerar lista de alunos com destaque acadêmico

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#133]
- [x] US1: Selecionar o curso. **Complexidade**: baixa. 🖼️
- [x] US2: Selecionar grupo de alunos concluintes. **Complexidade**: baixa. 🖼️ (implementado em #102 by @Lakshamana)
- [x] US3:  Selecionar botão de gerar lista de alunos com destaque acadêmico. **Complexidade**: baixa. 🖼️ (implementado em #146 by @Lakshamana)
- [x] US4: Consultar lista de alunos concluintes. **Complexidade**: baixa. 🏭 (implementado em #14)
- [x] US5: Selecionar alunos com atributo de destaque acadêmico. **Complexidade**: baixa. 🏭 (implementado em #14)
- [x] US6: Gerar lista de alunos com destaque acadêmico. **Complexidade**: baixa. 🖼️ (implementado em #146 by @Lakshamana)

**Comment by lubien** [comment]
Período é referente a Meta 13 e não deve ser trabalhado ainda.

**Comment by souzaluuk** [comment]
A US4 e US5 não são atendidas na requisição 
`GET api/students/?isConcluding=1&academicHighlight=1` ?

**Comment by souzaluuk** [comment]
Podem me tirar essa dúvida? 
@lubien 
@urielfcampos

**Comment by lubien** [comment]
Já tentou testar?

**Comment by souzaluuk** [comment]
Sim, e o resultado é o esperado.

**Comment by lubien** [comment]
@souzaluuk Issue fechada?

**Comment by Lakshamana** [comment]
@souzaluuk vem com o período de formaturaw

**Comment by souzaluuk** [comment]
US4 e US5 foram implementadas em #14.
Será adicionado um caso de teste específico pra este caso, visto que não existe.
