### ISSUE TITLE
Meta 20: Gerar lista de alterações que devem ser realizadas no Google Groups.

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#135]
- [x] US1: Selecionar curso. **Complexidade**: baixa
- [x] US2: Selecionar botão do email principal. **Complexidade**: baixa
- [ ] US3: Selecionar botão de alterações pendentes 🖼️. **Complexidade**: baixa
- [ ] US4: Abrir modal com as informações da lista de alterações pendentes. **Complexidade**: média.
- - [ ] Endpoint de comparação de presença na lista principal 🏭.
- - [ ] Modal de comparação 🖼️.
- [ ] US5: Selecionar botão Confirmar alterações. **Complexidade**: média.
- - Quando selecionado, todas as informações da lista de alterações pendentes deve ser excluída. Pois representa uma forma do usuário se certificar que já realizou as alterações que precisava.
- - [ ] Botão de confirmação 🖼️.
- - [ ] Endpoint de confirmação 🏭.

**Comment by lubien** [comment]
@urielfcampos 

[Rotas](https://github.com/projeto-spider/labes-2019/wiki/API:--Recurso-Estudantes#ver-mudan%C3%A7as-de-listas-de-email)
[Student](https://github.com/projeto-spider/labes-2019/wiki/API:-Student)

**Comment by lubien** [comment]
É só dar rebase no branch `m20-backend`
