### ISSUE TITLE
Controle da Sprint 04

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#136]
## Metas

- [x] Meta 04 (#130) 🏭: @daniel-santana (Implementado #143)
- [x] Meta 10 (#132) 🏭🖼️: @AndreMP93 @quaresmateo (Implementado em #141)
- [x] Meta 11 (#133) 🏭🖼️: @souzaluuk @Lakshamana (Implementado em #146)
- [x] Meta 20 (#135) 🏭🖼️: @lubien @urielfcampos (Implementado em #148)

## Correções

- [x] CRUD de pendências (#134, #83) 🏭🖼️: @souzaluuk @Lakshamana (implementado em #147)
- [x] Ocorreu erro no upload (#63)🖼️: @urielfcampos (Implementado em #138)

## Issues

- [x] O CD não está sendo salvo (#117)🖼️: @quaresmateo  (Implementado em #140)
- [x] Definir Licença (#61): @souzaluuk (Implementado em #139)

## Estudos

- [x] Geração de PDF (#137): @daniel-santana @jairofilho79
