### ISSUE TITLE
Meta 13: As listas do sistema devem ser separadas por períodos(ex: 2018.2).

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#153]
- [ ] Adicionar novo campo nas tabelas
- [ ] Listar alunos por período
- [ ] Integrar a divisão por período nas listas atuais.

**Comment by lubien** [comment]
Parcialmente implementado em #160

**Comment by lubien** [comment]
Isso aqui é especificamente front?

// @urielfcampos

**Comment by lubien** [comment]
Vale salientar que o cliente pediu modificações nos requisitos dessa meta.

// @ianCamposs

**Comment by urielfcampos** [comment]
@lubien Acredito que só falta o front disso aqui agora

**Comment by ianCamposs** [comment]
@lubien quais?

**Comment by lubien** [comment]
@ianCamposs Basicamente o Alan só quer que apareça o período no combo box e ele possa editar baseado em uma configuração global.

Isso é só a superfície, seria bom uma reunião

**Comment by ianCamposs** [comment]
@lubien , se isso ficar complicado pode deixar de lado, por que ele já mudou essa meta umas 2 vezes no mínimo.

**Comment by ianCamposs** [comment]
@lubien podemos reunir, sim

**Comment by lubien** [comment]
@ianCamposs ficou mais simples, na verdade
