### ISSUE TITLE
Meta 21 (Utilizado pelo Professor): Gerar dados do TCC utilizando formulário.

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#154]
- [x] US1: Logar na ferramenta Complexidade: baixa. (Implementado em #162)
- [x] US2: Preencher os dados do formulário Complexidade: baixa. (Implementado em #162)
- [x] US3:  Selecionar o botão de confirmar envio Complexidade: baixa. (Implementado em #162)

- US2
- - BR01: Para os campos de matrícula e nome deve ser possível adicionar mais uma instância para cada, visando atender os dados de TCC’s com dois orientandos. Sendo essa adição ativada com a seleção de um botão para adicionar novo.
- - BR02: Com exceção do coorientador e do avaliador 3, todos os outros campos são obrigatórios, inclusive a seleção de título e tipo de membro. 
- - BR03: Deve ser adicionado um combobox ao lado do preenchimento de nome dos participantes da banca(orientador,coorientador,avaliador 1, avaliador 2, avaliador 3), para selecionar o título(doutor, mestre, outro).
- - BR04: Deve ser adicionado um combobox ao lado do preenchimento de nome dos participantes da banca(orientador,coorientador,avaliador 1, avaliador 2, avaliador 3), para selecionar é membro externo ou interno. 
- US03
- - BR01: Caso orientador e coorientador estejam descritos como membro externo, a confirmação não deve ser permitida(Um dos dois deve ser membro interno).
