### ISSUE TITLE
Meta 22(Como Secretário): Confirmar dados da defesa de TCC e gerar documentos

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#155]
- [ ] US1: Selecionar botão de Defesa TCC's no menu lateral Complexidade: baixa
- [ ] US2: Selecionar o botão de Visualizar ao lado da Defesa de TCC(na lista de Defesas pendentes) que se deseja ver os dados Complexidade: baixa
- [ ] US3:  Abrir modal com informações da Defesa de TCC enviada Complexidade: baixa
- [ ] US4: Selecionar o botão de Confirmar Complexidade: baixa
- [ ] US5: A Defesa de TCC é movida de Pendente para Aceita Complexidade: baixa
- [ ] US6: Os documentos da defesa são gerados Complexidade: baixa

- US6: Os documentos da defesa são gerados
- - BR01: Os documentos gerados são: certificado do orientador, certificado do coorientador(caso tenha), certificado do avaliador 1, certificado do avaliador 2, certificado do avaliador 3(caso tenha), Ata, capa do CD e credenciamento de membro externo(caso tenha e para os que são).
