### ISSUE TITLE
Controle da Sprint 05

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#159]
## Metas
- [x] **Meta 19**: Alimentação do grupo de email de concluintes pela lista de alunos concluintes. #152
- [x] **Meta 21**: (Utilizado pelo Professor): Gerar dados do TCC utilizando formulário. #154
- [x] **Meta 22**: Meta 22(Como Secretário): Confirmar dados da defesa de TCC e gerar documentos #155 

## Correções
- [x] Fix bugs casos de teste v0.3.0
