### ISSUE TITLE
Controle Sprint 06

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#167]
## Metas
-  [x] Meta 26: Gerar documentos para a formatura #172 
-  [x] Meta 25: Gerar modelo de divulgação de Defesa de TCC #171 
-  [x] Meta 23 : Imprimir documentos gerados #169 
- [x] Meta 13: As listas do sistema devem ser separadas por períodos(ex: 2018.2). #153

## Mudanças requeridas pelo cliente:
- **Pagina de lista de email** #254
    - [x] Separar as abas de alteração em componentes separados: Alterações de inserção e Alterações de remoção
    - [x] refatorar componente para possuir um checkbox e confirmar as alterações só de alunos selecionados
    - [x] Possivelmente retirar as listas já que saiu do escopo.

- **Pagina de formandos**
  - [x] Remover botão de destaque acadêmico caso um já tenha sido selecionado. #252
  - [x] Adicionar Número de matrícula e e-mail na lista de prescrição #253 
  - [x] Alunos graduandos devem poder mudar entra aptos e não-aptos livremente

- **Formulário de admissão :**
   - [x] Adicionar curso e forma de ingresso
   - [x] refatorar o UI para ficar mais bonito 

- **Combo box do Aluno:**
   - [x] Mudar de pendências para disciplinas pendentes, adicionar contador de quantidade de disciplinas pendentes ao lado do botão
   - [x] Possivelmente mudar a cor do botão para vermelho
   - [x] Requerer uma confirmação ao atualizar o CRG para evitar possíveis erros
   - [x] Bug upload ata e Lauda 
   - [x] Campo CRG inativo/escondido para todos menos graduando apto #200 
   - [x] Relacionar data de defesa do aluno com a data de defesa do formulário de tcc.
   - [x] Relacionar orientador do aluno com o orientador do formulário de tcc

- [x] Zerar pendências do aluno quando mudar para status de **GRADUANDO** 
- [x] Esconder botão de pendências do aluno quando mudar para status de **GRADUANDO** 
- [x] Recarregar corretamente informações se ocorreu mudanças (Edições e etc)

**Comment by lubien** [comment]
Acabou
