### ISSUE TITLE
 Meta 23 : Imprimir documentos gerados

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#169]
- [ ] US1: Selecionar botão de Defesa TCC's no menu lateral🔴 Complexidade: baixa
- [ ] US2: Selecionar botão de visualizar ao lado da Defesa desejada(na lista de defesas Aceitas)🔴 Complexidade: baixa
- [ ] US3:  Selecionar botão de Imprimir todos ou impressão individual 🔴 Complexidade: baixa
- [ ] US4: Imprimir documentos selecionados Complexidade: baixa

**Comment by lubien** [comment]
Fazendo
