### ISSUE TITLE
Meta 24: Editar dados da Defesa de TCC

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#170]
- [x] US1: Selecionar botão de Defesa TCC's no menu lateral🔴 Complexidade: baixa (implementado em #163 )
- [x] US2: Selecionar botão de visualizar ao lado da defesa que deseja(podendo ser na lista de Pendentes , Aceitas e Realizadas)🔴 Complexidade: baixa (implementado em #163 )
- [x] US3:  Selecionar botão de Editar dentro do modal de visualização Complexidade: baixa (implementado em #163 )
- [x] US4: Editar dados da Defesa de TCC🔴 Complexidade: baixa (implementado em #163 )
- [x] US5: Selecionar botão de Confirmar alterações🔴 Complexidade: baixa (implementado em #163 )
