### ISSUE TITLE
Meta 25: Gerar modelo de divulgação de Defesa de TCC

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#171]
- [x] US1: Selecionar botão de Defesa TCC's no menu lateral🔴 Complexidade: baixa
- [x] US2: Selecionar o botão de Divulgação ao lado da Defesa desejada(somente permitido nas defesas da lista de Aceitas)🔴 Complexidade: baixa
- [x] US3:  Consultar dados da Defesa selecionada Complexidade: baixa
- [x] US4: Gerar modal com o modelo de Divulgação da Defesa de TCC Complexidade: baixa

**Comment by lubien** [comment]
Implementado em #221
