### ISSUE TITLE
Meta 26: Gerar documentos para a formatura

### ISSUE THREAD

**Issue by urielfcampos** [projeto-spider/labes-2019#172]
- [ ] US1: Selecionar botão de Formandos no menu lateral🔴 Complexidade: baixa
- [ ] US2: Selecionar botão de Gerar documentos de formatura🔴 Complexidade: baixa
- [ ] US3: Gerar modal com os documentos gerados Complexidade: baixa
- [ ] US4: Selecionar impressão de um ou mais documentos🔴Complexidade: baixa

**Comment by lubien** [comment]
Fazendo
