### ISSUE TITLE
Meta 01: Gerenciar de forma prática o acesso ao grupo do Google da faculdade.

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#2]
- [x] US1: Consultar a lista de alunos ativos. **Complexidade**: baixa (implementado em #14)
- - [x] Seleção de Curso 🖼️ #3
- - [x] Aba Alunos Ativos 🖼️ @Lakshamana
- - [x] Endpoint de lista de alunos 🏭 #4 @souzaluuk
- - [x] Filtro para nome, ativos e curso 🏭 @souzaluuk
- - [x] Página da aba 🖼️

- [x] US2: Filtrar somente os alunos com email "gmail". **Complexidade**: baixa
- [x] US3: Adicionar a Lista de email principal do Google . **Complexidade**: baixa
- [x] US4: Selecionar botão de gerar lista de email. 🖼️ @quaresmateo **Complexidade**: baixa.
- [x] US5: Gerar aba com a lista de email dos alunos. **Complexidade**: baixa.
- - [x] Adicionar botão de exportação na página de alunos ativos. 🖼️ @quaresmateo (Implementado em #112).
- - [x] Endpoint de geração da string. 🏭 @daniel-santana (Implementado em #100)

> Tarefa 1 movida para #92

> Tarefa 2 movida para #66

**Comment by lubien** [comment]
Meta em espera enquanto os requisitos são avaliados.

**Comment by lubien** [comment]
Como indicado por @ianCamposs, a suposta tarefa 1 foi modificada para a Meta 16 (#92).

Peço que os envolvidos (@quaresmateo e @souzaluuk) direcionem seu trabalho para ela.

**Comment by ianCamposs** [comment]
Meta 16 é onde alimentamos a lista de alunos ativos(aqui tem email gmail e outros tipos)
meta 1 é onde só tem email gmail e essa é o espelho do que deve ser no grupo do google

**Comment by lubien** [comment]
@ianCamposs então aqui haverá algum tipo de importação?

**Comment by ianCamposs** [comment]
Na meta 1 não, ele pega a lista da meta 16, então a importação está na meta 16

**Comment by ianCamposs** [comment]
Ele apenas filtra a lista dos alunos ativos

**Comment by lubien** [comment]
Perfeito

**Comment by lubien** [comment]
Atualizado para contemplar o modelo atual do documento de requisitos
