### ISSUE TITLE
Ordenação das Metas

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#22]
## Sprint 01
- [x] **Meta 06**: Adicionar alunos totais a ferramenta e direcioná-los de forma prática as suas respectivas listas de controle. #5 

## Sprint 02
- [x] **Meta 05**: Buscar informações sobre um aluno. #26 
- [x] **Meta 07**: Gerenciar arquivos, pendências e requisitos do aluno. #29 
- [x] **Meta 14**: As listas do sistema devem possuir ordenamento por
matrícula e nome. #30 
- [x] **Meta 15**: O sistema deve possuir um método de autenticação do usuário. #47 

## Sprint 03
- [x] **Meta 01**: Gerenciar de forma prática o acesso ao grupo do Google da faculdade. #2
- [x] **Meta 02**: Criação de formulário para acesso ao grupo de calouros. #123
- [x] **Meta 03**: Criação de formulário para acesso ao grupo de concluintes. #66 
- [x] **Meta 08**: Gerar de forma prática o destaque acadêmico. #68

## Sprint 04
- [x] **Meta 04**: Gerenciar de forma prática os status dos alunos graduandos. #130
- [x] **Meta 10**: Gerar lista de alunos presentes na lista de prescrição. #132
- [x] **Meta 11**: Gerar lista de alunos com destaque acadêmico. #133
- [x] **Meta 20**: Gerar lista de alterações que devem ser realizadas no Google Groups. #135

## Sprint 05
- [x] **Meta 13**: As listas do sistema devem ser separadas por períodos(ex: 2018.2). #153
- [x] **Meta 19**: Alimentação do grupo de email de concluintes pela lista de alunos concluintes. #152
- [x] **Meta 21**: (Utilizado pelo Professor): Gerar dados do TCC utilizando formulário. #154
- [x] **Meta 22**: Meta 22(Como Secretário): Confirmar dados da defesa de TCC e gerar documentos #155

## Para ser alocado
- [x] **Meta 12**: Alimentar de forma prática a lista de email.
- [x] **Meta 23**:(Como Secretário) Imprimir documentos gerados
- [x] **Meta 24** :(Como Secretário) Editar dados da Defesa de TCC
- [x] **Meta 25**:(Como Secretário) Gerar modelo de divulgação de Defesa de TCC
- [x] **Meta 26**:(Como Secretário)Gerar documentos para a formatura

**Comment by lubien** [comment]
Terminamos
