### ISSUE TITLE
Meta 15: O sistema deve possuir um método de autenticação do usuário

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#25]
- [x] Página de Login 🖼️
- - [x] Endpoint de login.
- [x] Lembrar último usuário.
- [x] Cadastrar usuários
- - [x] Página de cadastro 🖼️
- - [x] Endpoint de cadastro. 🏭
- [x] Middleware de Autenticação. 🖼️
- - [x] Middleware de Autenticação no Front. 🖼️
- - [x] Middleware de Autenticação no Back. 🏭
- [x] Persistir sessão. 🖼️
- [x] Verificar expiração do token. 🖼️

**Comment by lubien** [comment]
Implementado em #47
