### ISSUE TITLE
Meta 05: Buscar informações sobre um aluno.

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#26]
- [x] US1: Selecionar o curso. **Complexidade**: baixa (implementado em #14)
- [x] US2: Selecionar o botão de buscar aluno. **Complexidade**: baixa (implementado em #13)
- [x] US3: Informar o nome do alunos. **Complexidade**: média (implementado em #13)
- [x] US4: Gerar lista de resultados. **Complexidade**: baixa (implementado em #13)
- [x] US5: Selecionar aluno específico. **Complexidade**: baixa
- - [x] Clicar no nome do aluno 🖼️. (implementado em #37)
- [x] US6: Disponibilizar todas as informações sobre o aluno. **Complexidade**: baixa
- - [x] Combo Box do aluno 🖼️. (implementado em #37)
- [x] US7: Selecionar documento específico. **Complexidade**: baixa.  (implementado em #48 )
- [x] US8: Disponibilizar documento para visualização. **Complexidade**: alta (implementado em #48 )
- - [x] Visualizar PDF 🖼️.
- - [x] Endpoint de visualização de documentos (seguro para administradores) #28 🏭.
- [x] US9: Habilitar botão para baixar documento. **Complexidade**: baixa (implementado em #48 )
- - [x] Botão para baixar 🖼️.
- - [x] Endpoint de download de documentos (seguro para administradores) #28 🏭.
- [x] US10: Selecionar o botão de baixar o documento. **Complexidade**: baixa (implementado em #48 )
- [x] US11: Exportar o arquivo. **Complexidade**: alta (implementado em #48 )
