### ISSUE TITLE
Meta 07: Gerenciar arquivos, pendências e requisitos do aluno.

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#29]
- [x] US1: Selecionar curso **Complexidade**: baixa (implementado em #13)
- [x] US2: Buscar por aluno **Complexidade**: baixa (implementado em #13)
- [x] US3: Selecionar lista de alunos **Complexidade**: baixa (implementado em #13)
- [x] US4: Selecionar o aluno **Complexidade**: baixa (implementado em #13)
- [x] US5: Selecionar o botão de editar dentro do combo box de informações do aluno **Complexidade**: baixa. (Implementado #48 )
- - [x] Iniciar no modo de visualização 🖼️. 
- - [x] Entrar no modo de edição (ao clicar no botão "Editar" todos os campos viram editáveis e as caixas de texto ficam com o placeholder no valor atual) 🖼️.
- - [x] Endpoint de editar estudante 🏭.
- - [x] Endpoint de visualização de documentos (seguro para administradores) #28 🏭.
- - [x] Endpoint de upload de documento 🏭.
- [x] US6: Selecionar campo que deseja alterar 🖼️ **Complexidade**: baixa  (Implementado #48 )
- [x] US7: Selecionar botão para realizar upload de arquivo 🖼️ **Complexidade**: baixa  (Implementado #48 )
- [x] US8: Selecionar o arquivo desejado na máquina local 🖼️ **Complexidade**: baixa  (Implementado #48 )
- [x] US9: Realizar upload para a ferramenta **Complexidade**: média  (Implementado #48 )

## Business Rules

**BR01**: Em CD, Ata, Lauda e Lista de Prescrição deve haver um checkbox
**BR02**: Em CRG, Orientador e matérias pendentes deve haver um campo para digitar a informação

**Comment by lubien** [comment]
Atualizado para adicionar novas Business Rules (ver #27).

**Comment by fallennabicicleta** [comment]
Boa noite, na reunião de hoje com o Uriel, notei que faltou uma especificação nessa BR da US6, segue a BR e em negrito o que foi adicionado. Segue uma imagem do protótipo especificando melhor.
- BR02: Em CRG, Orientador, matérias pendentes e **data da defesa do TCC** deve haver um campo para digitar a informação**(OBS: O atributo “data da defesa do TCC” deve ser transferido para a coluna “Defendeu em” do respectivo aluno)**
![image](https://user-images.githubusercontent.com/29589264/57746960-d9f87480-76a9-11e9-8176-ca6cbd3aff11.png)
