### ISSUE TITLE
Meta 06: Adicionar alunos totais a ferramenta e direcioná-los de forma prática as suas respectivas listas de controle

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#5]
- [x] US1: Selecionar curso 🖼️ #3. **Complexidade**: baixa (implementado em #14)
- [x] US2: Selecionar botão de adicionar lista de alunos totais 🖼️🏭. **Complexidade**: baixa @daniel-santana 
- - [x] Botão da aba de importar alunos 🖼️ @urielfcampos (implementado em #13)
- - [x] Página da aba de importar alunos 🖼️ @urielfcampos (implementado em #13)

- [x] US3: Importar nova lista de alunos totais. **Complexidade**: média
- - [x] Upload de arquivo 🖼️ @urielfcampos  (implementado em #13)
- - [x] Endpoint de upload 🏭 @AndreMP93 @lubien (Implementado em #12)

- [x] US4: Atualizar lista de alunos totais. **Complexidade**: baixa
- - [x] Atualizar o banco 🏭 @AndreMP93 @lubien (Implementado em #9)

- [x] US5: Consultar lista de alunos totais. **Complexidade**: baixa
- - [x] Botão da aba de alunos totais 🖼️ @quaresmateo  (implementado em #13)
- - [x] Página da aba de alunos totais 🖼️ @quaresmateo  (implementado em #13)
- - [x] Endpoint de lista de alunos 🏭 #4 @souzaluuk (Implementado em #14)

- [x] US6: Adicionar aluno a lista de alunos formandos. **Complexidade**: baixa
- [x] US7: Adicionar aluno a lista de alunos ativos. **Complexidade:** baixa
- [x] US8: Mover a lista de alunos formandos. **Complexidade:** baixa
- [x] US9: Adicionar alunos a lista de alunos concluintes. **Complexidade:** baixa
- [x] US10: Mover a lista de alunos concluintes. **Complexidade:** baixa
- [x] US11: Adicionar aluno a lista de alunos graduandos não aptos.. **Complexidade:** baixa
- [x] US12: Adicionar aluno a lista de alunos ativos. **Complexidade:** baixa
- [x] US13: Mover a lista de alunos graduandos não aptos. **Complexidade:** baixa
- [x] US14: Adicionar aluno a lista de alunos ativos. **Complexidade:** baixa
