### ISSUE TITLE
Seleção de matérias para dependências dos alunos

### ISSUE THREAD

**Issue by lubien** [projeto-spider/labes-2019#83]
- [x] CRUD de matérias. (Implementado em #115)
- [x] Página de CRUD de matérias. (Implementado em #115)
- [x] Interface de seleção de matérias no modal do aluno. (Implementado em #147 )

**Comment by lubien** [comment]
Relacionado a #83
